### ISSUE TITLE
license

### ISSUE THREAD

**Issue by alexanderpanchenko** [CLLKazan/UIMA-Ext#6]
what is the license?

**Comment by rgareev** [comment]
The most of components are under Apache Software License v.2.
We are going to move others (that are integrated with libraries with a copyleft requirement, e.g., GPL) to a separate repository.

**Comment by alexanderpanchenko** [comment]
OK. So your code is ASLv2, right?

**Comment by rgareev** [comment]
Yep!

**Comment by alexanderpanchenko** [comment]
OK
